// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	dao "github.com/georgechang0117/url-shortener/core/dao"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// URLShortener is an autogenerated mock type for the URLShortener type
type URLShortener struct {
	mock.Mock
}

// Load provides a mock function with given fields: urlID
func (_m *URLShortener) Load(urlID string) (*dao.ShortLink, error) {
	ret := _m.Called(urlID)

	var r0 *dao.ShortLink
	if rf, ok := ret.Get(0).(func(string) *dao.ShortLink); ok {
		r0 = rf(urlID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.ShortLink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(urlID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: url, expireAt
func (_m *URLShortener) Upload(url string, expireAt time.Time) (*dao.ShortLink, error) {
	ret := _m.Called(url, expireAt)

	var r0 *dao.ShortLink
	if rf, ok := ret.Get(0).(func(string, time.Time) *dao.ShortLink); ok {
		r0 = rf(url, expireAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.ShortLink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(url, expireAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
